---
title: "DCLRE Data Exploration"
author: "Joe Mienko"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
---

## Project overview

The purpose of this project is to gain insight into the standards-based legal representation
pilot taking place in Washington State. 

All the results and plots presented in the pages below should be
reproduceable by an individual with access to the data sources. Follow the
[Setup Instructions](setup.html) if you are interested in reproducing
the results for yourself.

These are the results of current analyses.

1. [A first glance at the Divvy data.](first-glance.html) 

2. [A map of the Divvy stations in Chicago.](station-map.html)

3. [Exploring daily bike commuting trends from the Divvy
data.](time-of-day-trends.html)

4. [Exploring seasonal biking trends from the Divvy
data.](seasonal-trends.html)

## Credits

This workflowr project was developed by [Peter
Carbonetto](http://pcarbo.github.io) at the [University of
Chicago](https://www.uchicago.edu).

Thanks to [John Blischak](https://github.com/jdblischak) and
[Matthew Stephens](http://stephenslab.uchicago.edu) for their assistance and
support. Also, thanks to [Larry
Layne](https://rstudio-pubs-static.s3.amazonaws.com/63061_90f5136ffdf74740b6ba4ad8f2fd72fe.html)
and [Austin
Wehrwein](http://www.austinwehrwein.com/data-visualization/heatmaps-with-divvy-data)
for sharing their analyses of the Divvy trip data that inspired some
of the investigations here.
